import AppKit
import SwiftUI
import OSLog
import StillCore
import UniformTypeIdentifiers

@MainActor
final class AppModel: ObservableObject {
    @Published var items: [StillCore.LibraryItem] = []
    @Published var matches: [StillCore.LibraryItem] = []
    @Published var query = ""
    @Published var selectedID: UUID?
    @Published var showCapture = false
    @Published var showPreferences = false
    @Published var errorMessage: String?
    @Published var isPreparing = false
    @Published var captureEnabled = false {
        didSet {
            UserDefaults.standard.set(captureEnabled, forKey: "captureEnabled")
            // Starting capture never imports the clipboard that was already there.
            pasteboardChange = NSPasteboard.general.changeCount
        }
    }
    private var store: LibraryStore?
    private var timer: Timer?
    private var pasteboardChange = NSPasteboard.general.changeCount
    private var lastPrune = Date.distantPast
    private var preparedIDs = Set<UUID>()
    private let log = Logger(subsystem: "app.still.mac", category: "library")

    nonisolated static let excludedDefaults = """
    com.1password.1password
    com.agilebits.onepassword7
    com.apple.keychainaccess
    com.bitwarden.desktop
    com.lastpass.LastPass
    """
    nonisolated static let sensitiveTypes = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"
    ]

    init() {
        UserDefaults.standard.register(defaults: [
            "retentionDays": 7, "excludedApps": Self.excludedDefaults
        ])
        do {
            let root = try FileManager.default.url(for: .applicationSupportDirectory,
                                                    in: .userDomainMask, appropriateFor: nil, create: true)
            store = try LibraryStore(url: root.appendingPathComponent("Still/library.sqlite"))
            // Restrict local file access to this OS account. No application-level encryption yet.
            let directory = root.appendingPathComponent("Still")
            try FileManager.default.setAttributes([.posixPermissions: 0o700], ofItemAtPath: directory.path)
            try prune()
            reload()
        } catch {
            errorMessage = error.localizedDescription
            log.error("Library initialization failed; no reset performed.")
        }
        captureEnabled = UserDefaults.standard.bool(forKey: "captureEnabled")
        // A prior explicit opt-in persists, but capture always begins from current change count.
        timer = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.pollClipboard() }
        }
    }

    var isAvailable: Bool { store != nil }
    var selected: StillCore.LibraryItem? { items.first { $0.id == selectedID } }
    var sources: [String] { Array(Set(items.compactMap(\.sourceApp))).sorted() }

    func reload() {
        guard let store else { return }
        do {
            let all = try store.all()
            let found = query.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                ? all : try store.all(query: query)
            items = all
            matches = found
            if let selectedID, !all.contains(where: { $0.id == selectedID }) { self.selectedID = nil }
        } catch { report(error) }
    }

    @discardableResult
    func capture(_ text: String, title: String = "", manual: Bool = true,
                 source: NSRunningApplication? = nil) -> Bool {
        guard let store else { return false }
        do {
            let item = try store.capture(text: text, title: title, sourceApp: source?.localizedName,
                                         sourceBundleID: source?.bundleIdentifier, manual: manual)
            reload()
            if manual { selectedID = item.id }
            return true
        } catch { report(error); return false }
    }

    func update(_ item: StillCore.LibraryItem) {
        guard let store else { return }
        do {
            var value = item
            value.modifiedAt = Date()
            try store.save(value)
            reload()
        } catch { report(error) }
    }

    func delete(_ item: StillCore.LibraryItem) {
        guard let store else { return }
        do { try store.delete(id: item.id); reload() } catch { report(error) }
    }

    func copyOriginal(_ item: StillCore.LibraryItem) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(item.original, forType: .string)
        // Do not recapture Still's own copy action.
        pasteboardChange = NSPasteboard.general.changeCount
    }

    func openOriginal(_ item: StillCore.LibraryItem) {
        if let url = item.url { NSWorkspace.shared.open(url) }
    }

    func prepareReader(_ item: StillCore.LibraryItem) {
        guard let url = item.url, !preparedIDs.contains(item.id) else { return }
        if !item.annotations.isEmpty {
            errorMessage = "This item has annotations. Keep its current snapshot so their context stays intact."
            return
        }
        preparedIDs.insert(item.id)
        isPreparing = true
        Task {
            defer {
                preparedIDs.remove(item.id)
                isPreparing = !preparedIDs.isEmpty
            }
            do {
                let article = try await ArticleLoader.load(url)
                guard var latest = items.first(where: { $0.id == item.id }) else { return }
                // An annotation added during download must also preserve its original context.
                guard latest.annotations.isEmpty else { return }
                latest.articleText = article.text
                latest.snapshotAt = Date()
                latest.readingOffset = 0
                latest.status = .reading
                if latest.title == url.host, !article.title.isEmpty { latest.title = article.title }
                update(latest)
            } catch {
                report(error)
            }
        }
    }

    func addAnnotation(item: StillCore.LibraryItem, range: NSRange) {
        let text = item.readingText as NSString
        guard range.location != NSNotFound, range.length > 0,
              range.location <= text.length, range.length <= text.length - range.location else { return }
        var value = item
        value.annotations.append(Annotation(quote: text.substring(with: range), range: range))
        // Annotated items never expire with temporary clipboard history.
        value.isKept = true
        update(value)
    }

    func savePosition(id: UUID, offset: Double) {
        guard var value = items.first(where: { $0.id == id }), abs(value.readingOffset - offset) > 4 else { return }
        value.readingOffset = max(0, offset)
        update(value)
    }

    func exportLibrary() {
        guard let store else { return }
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.json]
        panel.nameFieldStringValue = "Still-library.json"
        guard panel.runModal() == .OK, let url = panel.url else { return }
        do { try store.exportData().write(to: url, options: .atomic) } catch { report(error) }
    }

    func importLibrary() {
        guard let store else { return }
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.json]
        panel.allowsMultipleSelection = false
        guard panel.runModal() == .OK, let url = panel.url else { return }
        do {
            let attributes = try FileManager.default.attributesOfItem(atPath: url.path)
            guard ((attributes[.size] as? NSNumber)?.intValue ?? Int.max) <= 100_000_000 else {
                throw StoreError(message: "Choose an archive smaller than 100 MB.")
            }
            try store.importData(Data(contentsOf: url))
            reload()
        } catch { report(error) }
    }

    func pruneNow() {
        do { try prune(); reload() } catch { report(error) }
    }

    private func prune() throws {
        try store?.prune(retentionDays: UserDefaults.standard.integer(forKey: "retentionDays"))
        lastPrune = Date()
    }

    private func pollClipboard() {
        if Date().timeIntervalSince(lastPrune) > 3600 { pruneNow() }
        let pasteboard = NSPasteboard.general
        guard captureEnabled, store != nil, pasteboard.changeCount != pasteboardChange else { return }
        pasteboardChange = pasteboard.changeCount
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard !Self.sensitiveTypes.contains(where: types.contains) else { return }
        let source = NSWorkspace.shared.frontmostApplication
        guard source?.processIdentifier != ProcessInfo.processInfo.processIdentifier else { return }
        let excluded = Set((UserDefaults.standard.string(forKey: "excludedApps") ?? "")
            .split(whereSeparator: { $0.isWhitespace }).map(String.init))
        guard !excluded.contains(source?.bundleIdentifier ?? "") else { return }
        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.utf8.count <= 1_000_000 else { return }
        // Frontmost app is an estimate, not a guaranteed clipboard author.
        _ = capture(text, manual: false, source: source)
    }

    private func report(_ error: Error) {
        errorMessage = error.localizedDescription
        log.error("Library operation failed. Saved content omitted from diagnostics.")
    }
}
